INSERT INTO criteria (description) VALUES ('None');
INSERT INTO criteria (description) VALUES ('immediately given the clue');
INSERT INTO criteria (description) VALUES ('in five minutes');
INSERT INTO criteria (description) VALUES ('in ten minutes');
INSERT INTO criteria (description) VALUES ('5 minimum');
INSERT INTO criteria (description) VALUES ('10 minimum');
INSERT INTO criteria (description) VALUES ('15 minimum');
INSERT INTO criteria (description) VALUES ('20 minimum');
INSERT INTO criteria (description) VALUES ('30 minimum');
INSERT INTO criteria (description) VALUES ('50 minimum');
INSERT INTO criteria (description) VALUES ('100 minimum');
INSERT INTO criteria (description) VALUES ('in an array of 2');
INSERT INTO criteria (description) VALUES ('in an array of 3');
INSERT INTO criteria (description) VALUES ('in an array of 5');
INSERT INTO criteria (description) VALUES ('in an array of 7');
INSERT INTO criteria (description) VALUES ('in an array of 10');
INSERT INTO criteria (description) VALUES ('in a large array');
INSERT INTO criteria (description) VALUES ('across three sessions');
INSERT INTO criteria (description) VALUES ('across five sessions');