INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'None', 0);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 1 session', 1);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 2 session', 2);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 3 session', 3);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 4 session', 4);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 5 session', 5);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 6 session', 6);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 7 session', 7);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 8 session', 8);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 9 session', 9);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 10 session', 10);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 11 session', 11);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 12 session', 12);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 13 session', 13);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 14 session', 14);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 15 session', 15);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 16 session', 16);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 17 session', 17);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 18 session', 18);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 19 session', 19);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 20 session', 20);

INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, 'None', 0);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '1 consecutive session', 1);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '2 consecutive sessions', 2);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '3 consecutive sessions', 3);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '4 consecutive sessions', 4);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '5 consecutive sessions', 5);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '6 consecutive sessions', 6);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '7 consecutive sessions', 7);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '8 consecutive sessions', 8);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '9 consecutive sessions', 9);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '10 consecutive sessions', 10);
