INSERT INTO conditions (description) VALUES ('None');
INSERT INTO conditions (description) VALUES ('given a choice');
INSERT INTO conditions (description) VALUES ('given no assistance');
INSERT INTO conditions (description) VALUES ('given partial verbal prompt');
INSERT INTO conditions (description) VALUES ('given two verbal prompts');
INSERT INTO conditions (description) VALUES ('given a visual prompt');
INSERT INTO conditions (description) VALUES ('given demonstration');
INSERT INTO conditions (description) VALUES ('given a model prompt');
INSERT INTO conditions (description) VALUES ('given partial physical prompt');
INSERT INTO conditions (description) VALUES ('given full physical prompt');
INSERT INTO conditions (description) VALUES ('given one verbal prompt');
INSERT INTO conditions (description) VALUES ('given a written prompt');
INSERT INTO conditions (description) VALUES ('given adult facilitation');
INSERT INTO conditions (description) VALUES ('given a cue');
