INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'None', 0);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 1 session', 1);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 2 sessions', 2);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 3 sessions', 3);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 4 sessions', 4);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 5 sessions', 5);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 6 sessions', 6);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 7 sessions', 7);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 8 sessions', 8);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 9 sessions', 9);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 10 sessions', 10);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 11 sessions', 11);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 12 sessions', 12);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 13 sessions', 13);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 14 sessions', 14);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 15 sessions', 15);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 16 sessions', 16);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 17 sessions', 17);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 18 sessions', 18);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 19 sessions', 19);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (2, 'across 20 sessions', 20);

INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, 'None', 0);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '1 consecutive session', 1);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '2 consecutive sessions', 2);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '3 consecutive sessions', 3);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '4 consecutive sessions', 4);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '5 consecutive sessions', 5);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '6 consecutive sessions', 6);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '7 consecutive sessions', 7);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '8 consecutive sessions', 8);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '9 consecutive sessions', 9);
INSERT INTO criteria (objective_type_id, description, consecutive_to_mastered) VALUES (1, '10 consecutive sessions', 10);
